# Config file for automatic testing at travis-ci.org

language: python

# Use container based infrastructure
sudo: false

env:
  - TOXENV=py26-dj16
  - TOXENV=py27-dj16
  - TOXENV=py27-dj17
  - TOXENV=flake8

cache:
  directories:
    - $HOME/.wheelhouse

install:
  - pip install tox
  - pip install coveralls

script:
  - tox

after_success: coveralls

notifications:
  webhooks: http://aldryn-addons.com/en/travis-endpoint/
