# Config file for automatic testing at travis-ci.org

language: python

# Use container based infrastructure
sudo: false

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

env:
  matrix:
  - DJANGO=1.6 CMD=./test
  - DJANGO=1.7 CMD=./test
  - DJANGO=1.8 CMD=./test

matrix:
  allow_failures:
    - python: 3.3
    - python: 3.4
    - env: DJANGO=1.8 CMD=./test
  exclude:
    - python: 2.6
      env: DJANGO=1.7 CMD=./test
    - python: 2.6
      env: DJANGO=1.8 CMD=./test
  fast_finish: true
  include:
    - python: 2.7
      env: DJANGO=1.7 CMD="flake8 aldryn_newsblog"

cache:
  directories:
    - $HOME/.wheelhouse

install:
  - pip install coveralls
  - pip install -r "test_requirements/django-$DJANGO.txt"

script: coverage run test_settings.py

after_success: coveralls

notifications:
  webhooks: http://aldryn-addons.com/en/travis-endpoint/
